
import { PlayerData } from './types';

export const INITIAL_PLAYER_DATA: PlayerData = {
  name: "ERLING HAALAND",
  club: "Manchester City",
  nationality: "Norway",
  position: "ST",
  age: 23,
  photoUrl: "https://images.unsplash.com/photo-1511367461989-f85a21fda167?w=800&q=80",
  photoZoom: 1,
  photoX: 0,
  photoY: 0,
  clubLogoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/200px-Manchester_City_FC_badge.svg.png",
  nationFlagUrl: "https://flagcdn.com/w160/no.png",
  primaryColor: "#6CADDF",
  secondaryColor: "#1C2C5B",
  backgroundMode: 'blur',
  customBgUrl: "",
  customBgBlur: 0,
  customBgOpacity: 0.4,
  blurIntensity: 40,
  bgOpacity: 0.2,
};

export const POSITIONS = [
  "GK", "SW", "LB", "CB", "RB", "LWB", "RWB", "DM", "LM", "CM", "RM", "AM", "LW", "RW", "ST"
];

export const COUNTRIES = [
  { name: "Afghanistan", code: "af" }, { name: "Albania", code: "al" }, { name: "Algeria", code: "dz" },
  { name: "American Samoa", code: "as" }, { name: "Andorra", code: "ad" }, { name: "Angola", code: "ao" },
  { name: "Anguilla", code: "ai" }, { name: "Antigua and Barbuda", code: "ag" }, { name: "Argentina", code: "ar" },
  { name: "Armenia", code: "am" }, { name: "Aruba", code: "aw" }, { name: "Australia", code: "au" },
  { name: "Austria", code: "at" }, { name: "Azerbaijan", code: "az" }, { name: "Bahamas", code: "bs" },
  { name: "Bahrain", code: "bh" }, { name: "Bangladesh", code: "bd" }, { name: "Barbados", code: "bb" },
  { name: "Belarus", code: "by" }, { name: "Belgium", code: "be" }, { name: "Belize", code: "bz" },
  { name: "Benin", code: "bj" }, { name: "Bermuda", code: "bm" }, { name: "Bhutan", code: "bt" },
  { name: "Bolivia", code: "bo" }, { name: "Bosnia and Herzegovina", code: "ba" }, { name: "Botswana", code: "bw" },
  { name: "Brazil", code: "br" }, { name: "British Virgin Islands", code: "vg" }, { name: "Brunei", code: "bn" },
  { name: "Bulgaria", code: "bg" }, { name: "Burkina Faso", code: "bf" }, { name: "Burundi", code: "bi" },
  { name: "Cambodia", code: "kh" }, { name: "Cameroon", code: "cm" }, { name: "Canada", code: "ca" },
  { name: "Cape Verde", code: "cv" }, { name: "Cayman Islands", code: "ky" }, { name: "Central African Republic", code: "cf" },
  { name: "Chad", code: "td" }, { name: "Chile", code: "cl" }, { name: "China", code: "cn" },
  { name: "Colombia", code: "co" }, { name: "Comoros", code: "km" }, { name: "Congo", code: "cg" },
  { name: "Cook Islands", code: "ck" }, { name: "Costa Rica", code: "cr" }, { name: "Croatia", code: "hr" },
  { name: "Cuba", code: "cu" }, { name: "Curaçao", code: "cw" }, { name: "Cyprus", code: "cy" },
  { name: "Czech Republic", code: "cz" }, { name: "Denmark", code: "dk" }, { name: "Djibouti", code: "dj" },
  { name: "Dominica", code: "dm" }, { name: "Dominican Republic", code: "do" }, { name: "Ecuador", code: "ec" },
  { name: "Egypt", code: "eg" }, { name: "El Salvador", code: "sv" }, { name: "England", code: "gb-eng" },
  { name: "Equatorial Guinea", code: "gq" }, { name: "Eritrea", code: "er" }, { name: "Estonia", code: "ee" },
  { name: "Eswatini", code: "sz" }, { name: "Ethiopia", code: "et" }, { name: "Faroe Islands", code: "fo" },
  { name: "Fiji", code: "fj" }, { name: "Finland", code: "fi" }, { name: "France", code: "fr" },
  { name: "Gabon", code: "ga" }, { name: "Gambia", code: "gm" }, { name: "Georgia", code: "ge" },
  { name: "Germany", code: "de" }, { name: "Ghana", code: "gh" }, { name: "Gibraltar", code: "gi" },
  { name: "Greece", code: "gr" }, { name: "Grenada", code: "gd" }, { name: "Guam", code: "gu" },
  { name: "Guatemala", code: "gt" }, { name: "Guinea", code: "gn" }, { name: "Guinea-Bissau", code: "gw" },
  { name: "Guyana", code: "gy" }, { name: "Haiti", code: "ht" }, { name: "Honduras", code: "hn" },
  { name: "Hong Kong", code: "hk" }, { name: "Hungary", code: "hu" }, { name: "Iceland", code: "is" },
  { name: "India", code: "in" }, { name: "Indonesia", code: "id" }, { name: "Iran", code: "ir" },
  { name: "Iraq", code: "iq" }, { name: "Ireland", code: "ie" }, { name: "Israel", code: "il" },
  { name: "Italy", code: "it" }, { name: "Ivory Coast", code: "ci" }, { name: "Jamaica", code: "jm" },
  { name: "Japan", code: "jp" }, { name: "Jordan", code: "jo" }, { name: "Kazakhstan", code: "kz" },
  { name: "Kenya", code: "ke" }, { name: "Kosovo", code: "xk" }, { name: "Kuwait", code: "kw" },
  { name: "Kyrgyzstan", code: "kg" }, { name: "Laos", code: "la" }, { name: "Latvia", code: "lv" },
  { name: "Lebanon", code: "lb" }, { name: "Lesotho", code: "ls" }, { name: "Liberia", code: "lr" },
  { name: "Libya", code: "ly" }, { name: "Liechtenstein", code: "li" }, { name: "Lithuania", code: "lt" },
  { name: "Luxembourg", code: "lu" }, { name: "Macau", code: "mo" }, { name: "Madagascar", code: "mg" },
  { name: "Malawi", code: "mw" }, { name: "Malaysia", code: "my" }, { name: "Maldives", code: "mv" },
  { name: "Mali", code: "ml" }, { name: "Malta", code: "mt" }, { name: "Mauritania", code: "mr" },
  { name: "Mauritius", code: "mu" }, { name: "Mexico", code: "mx" }, { name: "Moldova", code: "md" },
  { name: "Monaco", code: "mc" }, { name: "Mongolia", code: "mn" }, { name: "Montenegro", code: "me" },
  { name: "Montserrat", code: "ms" }, { name: "Morocco", code: "ma" }, { name: "Mozambique", code: "mz" },
  { name: "Myanmar", code: "mm" }, { name: "Namibia", code: "na" }, { name: "Nepal", code: "np" },
  { name: "Netherlands", code: "nl" }, { name: "New Caledonia", code: "nc" }, { name: "New Zealand", code: "nz" },
  { name: "Nicaragua", code: "ni" }, { name: "Niger", code: "ne" }, { name: "Nigeria", code: "ng" },
  { name: "North Korea", code: "kp" }, { name: "North Macedonia", code: "mk" }, { name: "Northern Ireland", code: "gb-nir" },
  { name: "Norway", code: "no" }, { name: "Oman", code: "om" }, { name: "Pakistan", code: "pk" },
  { name: "Palestine", code: "ps" }, { name: "Panama", code: "pa" }, { name: "Papua New Guinea", code: "pg" },
  { name: "Paraguay", code: "py" }, { name: "Peru", code: "pe" }, { name: "Philippines", code: "ph" },
  { name: "Poland", code: "pl" }, { name: "Portugal", code: "pt" }, { name: "Puerto Rico", code: "pr" },
  { name: "Qatar", code: "qa" }, { name: "Romania", code: "ro" }, { name: "Russia", code: "ru" },
  { name: "Rwanda", code: "rw" }, { name: "Saint Kitts and Nevis", code: "kn" }, { name: "Saint Lucia", code: "lc" },
  { name: "Samoa", code: "ws" }, { name: "San Marino", code: "sm" }, { name: "Saudi Arabia", code: "sa" },
  { name: "Scotland", code: "gb-sct" }, { name: "Senegal", code: "sn" }, { name: "Serbia", code: "rs" },
  { name: "Seychelles", code: "sc" }, { name: "Sierra Leone", code: "sl" }, { name: "Singapore", code: "sg" },
  { name: "Slovakia", code: "sk" }, { name: "Slovenia", code: "si" }, { name: "Solomon Islands", code: "sb" },
  { name: "Somalia", code: "so" }, { name: "South Africa", code: "za" }, { name: "South Korea", code: "kr" },
  { name: "South Sudan", code: "ss" }, { name: "Spain", code: "es" }, { name: "Sri Lanka", code: "lk" },
  { name: "Sudan", code: "sd" }, { name: "Suriname", code: "sr" }, { name: "Sweden", code: "se" },
  { name: "Switzerland", code: "ch" }, { name: "Syria", code: "sy" }, { name: "Tahiti", code: "pf" },
  { name: "Taiwan", code: "tw" }, { name: "Tajikistan", code: "tj" }, { name: "Tanzania", code: "tz" },
  { name: "Thailand", code: "th" }, { name: "Togo", code: "tg" }, { name: "Tonga", code: "to" },
  { name: "Trinidad and Tobago", code: "tt" }, { name: "Tunisia", code: "tn" }, { name: "Turkey", code: "tr" },
  { name: "Turkmenistan", code: "tm" }, { name: "Turks and Caicos Islands", code: "tc" }, { name: "Uganda", code: "ug" },
  { name: "Ukraine", code: "ua" }, { name: "United Arab Emirates", code: "ae" }, { name: "USA", code: "us" },
  { name: "Uruguay", code: "uy" }, { name: "Uzbekistan", code: "uz" }, { name: "Vanuatu", code: "vu" },
  { name: "Venezuela", code: "ve" }, { name: "Vietnam", code: "vn" }, { name: "Wales", code: "gb-wls" },
  { name: "Yemen", code: "ye" }, { name: "Zambia", code: "zm" }, { name: "Zimbabwe", code: "zw" }
].sort((a, b) => a.name.localeCompare(b.name));
